### ISSUE TITLE
Not compatible with model relations?

### ISSUE THREAD

**Issue by TheTechnoMan** [pingpong-labs/modules#102]
Hey,

I added a relation to my model like that:
```
    public function articles()
    {
        return $this->hasMany('App\Modules\XXX\Models\Articles');
    }
```

But always get:

FatalErrorException in Model.php line 902: Class 'App\Modules\XXX\Models\Articles' not found

Am I doing something wrong, or is the package not compatible with relations?

Thanks!

**Comment by nWidart** [comment]
It is compatible with model relations. 

You've got to make sure your module is correctly loaded and accessible.

**Comment by TheTechnoMan** [comment]
No idea then what is going wrong. I just specified the full namespace, do I need to manually load the file somewhere?

Thanks!

**Comment by nWidart** [comment]
How do you autoload your modules ?

**Comment by TheTechnoMan** [comment]
Not sure what exactly you mean. The ModuleServiceProvider does that.

**Comment by nWidart** [comment]
This is how you could autoload them: https://github.com/nWidart/Laravel-Broadway-Demo/blob/master/composer.json#L29

**Comment by TheTechnoMan** [comment]
Yes, this is what I do. As I said, everything works except for the model relations.

**Comment by nWidart** [comment]
In that case you should double check the class name. Check if the file name correspond (case differences etc.)

**Comment by TheTechnoMan** [comment]
That is the weird thing. I just copied the namespace. It is also working when I use it like Model::XX, just not in the relation (in the question). No idea why,, :(

**Comment by TheTechnoMan** [comment]
Maybe it has something to do with the fact that the model is not in the same module?

**Comment by TheTechnoMan** [comment]
Nevermind, I think I found it. Will let you know!

**Comment by TheTechnoMan** [comment]
Was my bad. Thanks!
