### ISSUE TITLE
"use" not working

### ISSUE THREAD

**Issue by TheTechnoMan** [pingpong-labs/modules#103]
```
php artisan module:use Test
Module [Test] has been used for current session.

php artisan make:migration test
Created Migration: 2015_02_16_033307_test
```

It does NOT create it in the modules database/migrations directory but in the main one.

**Comment by gravitano** [comment]
What version are you using ? I have tested in my environment and all goes well.

**Comment by TheTechnoMan** [comment]
The most up to date 2.0 version. Just tried it again, it still creates it in the /app directory :/

**Comment by gravitano** [comment]
Hmm weird. Try to remove the package and install again from scratch.

**Comment by TheTechnoMan** [comment]
Cant really do that. Just wanted to let it know ;)

**Comment by gravitano** [comment]
I've tested this command and all goes well. Just make sure your storage path is writable.
