### ISSUE TITLE
Published asset folder : lowercase

### ISSUE THREAD

**Issue by nWidart** [pingpong-labs/modules#105]
Could you please make the published assets folder lowercase ? As this causes issues on case sensitive OS's.

Thanks!

**Comment by gravitano** [comment]
That for the feedback. I'll add this as a feature request. Thanks

**Comment by nWidart** [comment]
Could you please try to fix this? This issue is blocking us on our staging server.

Thanks

**Comment by nWidart** [comment]
Awesome! :+1:
