### ISSUE TITLE
Noob help - pingpong admin @create

### ISSUE THREAD

**Issue by 4ccoun7** [pingpong-labs/modules#110]
Hello.

I cant find a manual or anything on the pingpong admin, and im pretty new to Laravel too.
Im creating custom tables to the backend, and ive got one issue that is taking me forever.

Everything pretty much works, except creating /views/newtable/create
Undefined variable: xxxxxxxxxx (View: /home/vagrant/Sites/sitename/laravel/vendor/pingpong/admin/src/views/newtable/form.blade.php) (View: /home/vagrant/Sites/sitename/laravel/vendor/pingpong/admin/src/views/newtable/form.blade.php)

The thing is, i cant atm figure out how " $categories " is being called in articles/form.blade.php ??? ->

	@if(Request::is('admin/articles/create'))
	<div class="form-group">
		{{ Form::label('category_id', 'Category:') }}
		{{ Form::select('category_id', >>>>    $categories      <<<<<, null, ['class' => 'form-control']) }}
		{{ $errors->first('category_id', '<div class="text-danger">:message</div>') }}
	</div>
	@else
	{{ Form::hidden('type', 'page') }}
	@endif

Hope it makes a little sence, and really hope i someone can helo me out,

Best regards,
Christian

**Comment by gravitano** [comment]
Hi,

The `categories` variable were taken from [ArticleFormComposer](https://github.com/pingpong-labs/admin/blob/master/src/Pingpong/Admin/Composers/ArticleFormComposer.php) class which uses the technique of Laravel View Composer. You can learn about the view composer [here](http://laravel.com/docs/4.2/responses#view-composers).

**Comment by 4ccoun7** [comment]
Thanks alot! It seems to be where the problem gets solved, but it doesnt work for me :-S

<?php namespace Pingpong\Admin\Composers;
use Pingpong\Admin\Entities\NewCategory;

class NewFormComposer {

    public function compose($view)
    {
        $newcategories = NewCategory::lists('name', 'id');

        $view->with(compact('newcategories'));
    }
}

		{{ Form::label('category_id', 'Category:') }}
		{{ Form::select('category_id', $newcategories, null, ['class' => 'form-control']) }}
		{{ $errors->first('category_id', '<div class="text-danger">:message</div>') }}


ErrorException (E_UNKNOWN) 
Undefined variable: newcategories


Its a total replica of the original, with database and everything .. Hmm, whats wrong here ?

**Comment by 4ccoun7** [comment]
Got it :-) !
