### ISSUE TITLE
Articles replica - newArticles doesn't fetch newArticlePages

### ISSUE THREAD

**Issue by 4ccoun7** [pingpong-labs/modules#111]
Hello!
/admin/newArticles/create
Cant figure how to relate my newArticles category, with newArticlePages. newArticlePages do not appear in Categories while attempting to fetch newArticle article to the correct newArticlePage.
- hope it makes sense...

Where should i look- debug ?

Best regards,
Christian!

**Comment by 4ccoun7** [comment]
Bump :-/

**Comment by nWidart** [comment]
You shouldn't bump your own issues. Even less the same day. People have jobs.

**Comment by 4ccoun7** [comment]
Thanks alot for your precious time, i almost thought someone where here to help me with my problem!

**Comment by 4ccoun7** [comment]
Other suggestion if im lacking experience with PHP ? Do i have to read a book before i can finish my project?

**Comment by nWidart** [comment]
With your problem related to `pingpong/modules`... which this isn't.

**Comment by 4ccoun7** [comment]
Im new........ And this problem is related to pingpong admin, should i 'try' and find the solution on Laravel Docs, or should i ask here - hopefully someone know, and can help me, i have used sevel hours today trying to find the bug and now im pretty much hoping to get help here :-/ .

My only question is, where and how does Pages get attached to > Article Category.

Because i cant seem to find the problem, i looked at very file .

**Comment by noxify** [comment]
Hi,

i don't think this is a modules related problem, but maybe we can help you ;)

What I understand:

* You're using the Admin Package
* You're using the Modules Package
* You're using the Articles "Module" and Categories "Module" which comes directly with the Admin Package
* You're trying to create a relation between a category and a Page (Article from type page)

If I'm not wrong, you only have to update the conditions in the view:
https://github.com/pingpong-labs/admin/blob/master/src/views/articles/form.blade.php
(create a copy of this in your app/views directory)

The Models (Entities/Article.php and Entities/Category.php) have already the correct relation and in the Articles Controller there is no type check (Article or page) it's only in the view.

Correct me please, if I have understood something wrong.

Bump end ;)

Greets,
Marcus
