### ISSUE TITLE
Tabs in generated migrations

### ISSUE THREAD

**Issue by fgreinus** [pingpong-labs/modules#121]
Today I noticed, that when one generates migrations via the command (php artisan module:migration create_example_table for example), there are tabs in it (instead of spaces).

When generating models there are spaces in it (as far as I noticed). So I'd appreciate if this could be changed to spaces instead of tabs... because tabs suck :trollface:

**Comment by gravitano** [comment]
Is this question talk about indentation ? If you prefer using space instead of tab, you can reformat your code manually.

**Comment by nWidart** [comment]
That's what I do too.:)

Would you consider switcher to PSR-2, once Laravel has too (in version `5.1`) ? :smile:

**Comment by gravitano** [comment]
I don't know. I would consider it.

**Comment by fgreinus** [comment]
I was just asking, because I had the impression, that there are both things used. But in case it's only tabs - this issue can obsiously be closed :).
I wouldn't start switching to spaces before laravel did it...
