### ISSUE TITLE
Migration class not found after module:migration

### ISSUE THREAD

**Issue by nWidart** [pingpong-labs/modules#128]
Hello,

I'm getting a class not found error:
``` php
 Class 'CreateBlockBlocksTable' not found 
```
When running `artisan module:migrate`, but that class does exist.

![screen shot 2015-04-01 at 7 45 15 pm](https://cloud.githubusercontent.com/assets/882397/6947441/ac05a02e-d8a7-11e4-8c02-3cb1b7645a75.png)

I've tried running `artisan clear-compiled`, `composer dump-autoload`, `composer du`, create a new temporary migration (to reload the migrations maybe), nothing fixes it.

Anything I forgot ? Or anything I can do to 'rescan' the migrations folder ?

Thanks,

**Comment by gravitano** [comment]
Is that migration loaded from an enabled module ?

**Comment by nWidart** [comment]
The module is enabled, yes.

I think the reason is I didn't make that migration using the artisan command, but by using a stub file to create it during my `asgard:module:scaffold` command. 

Weird laravel can't find it even after all those dump autoload etc. 
I'd much prefer creating that migration llike I'm doing now instead of calling the artisan command so I can customize the file as I please.
