### ISSUE TITLE
pingpong/generators 2.0.*@dev error on composer update

### ISSUE THREAD

**Issue by abinvp** [pingpong-labs/modules#132]
I have been using 2.0.*@dev and while updating composer I got the following error. 
   - Installation request for pingpong/modules 2.0.*@dev -> satisfiable by pingpong/modules[2.0.x-dev].
   - pingpong/modules 2.0.x-dev requires pingpong/generators 2.0.*@dev -> no matching package found.

Changing the version to 2.0.x-dev and manually adding "pingpong/generators": "2.0.*@dev" have fixed the issue. Would be great if it could be included in the modules package.

**Comment by nWidart** [comment]
Do you have

``` json
"minimum-stability": "dev",
``` 
set in your composer.json file ?

**Comment by abinvp** [comment]
Ah I was missing that. Thanks for the help @nWidart

**Comment by nWidart** [comment]
Awesome :+1:
