### ISSUE TITLE
Error when composer update.

### ISSUE THREAD

**Issue by DevCoder31** [pingpong-labs/modules#134]
Hello, 
I get this error when updating with composer. i tried with a new fresh install and i get the same problem.
This is the error message.
 Problem 1
   - Installation request for pingpong/modules 2.0.*@dev -> satisfiable by pingpong/modules[2.0.x-dev].
   - pingpong/modules 2.0.x-dev requires pingpong/generators 2.0.*@dev -> no matching package found.

Thank you.
Best Regards.

**Comment by nWidart** [comment]
Hello, you need to add the following to your composer.json file:

```json
"minimum-stability": "dev",
"prefer-stable": true
```

**Comment by DevCoder31** [comment]
Hello, 
I did it but i get the same error message.
Thank you.

**Comment by gravitano** [comment]
Try add `pingpong/generators:2.0.*@dev` manually to your `composer.json` file.

**Comment by DevCoder31** [comment]
Hi, it seems that it's working now thank you :)
