### ISSUE TITLE
NotFoundHttpException after getting published module

### ISSUE THREAD

**Issue by virtualstep** [pingpong-labs/modules#136]
Hello,

after I created a module I published it to my private git repo.
After that I installed it via composer and it's available at the vendor folder, now.
But when I open my Browser and type an route in, which is available in route.php file i get a 

NotFoundHttpException in RouteCollection.php line 145

composer dump-autoload has no effect.

Can u help me? Sorry for my bad english. I'm German.

Greetings.

**Comment by virtualstep** [comment]
Same Problem with module in "module" - folder.

**Comment by gravitano** [comment]
Have you added new Service provider
'Pingpong\Modules\Providers\BootstrapServiceProvider' to your config file ?

**Comment by virtualstep** [comment]
Hey,

I done this but now I get the error

Class 'Modules\Admin\Providers\AdminServiceProvider' not found

After that I created a new module named test...module created, but then I get the same error for this module!

**Comment by ottowayne** [comment]
Yeah, you have to add the new BootstrapServiceProvider.

I would suggest not writing to use "2.0.*@dev" in the documentation if there are breaking changes like this.

**Comment by virtualstep** [comment]
But with this provider I will have a new problem ...

**Comment by gravitano** [comment]
New problem ? PSR-4 autoloading, maybe ?

**Comment by virtualstep** [comment]
No I think.

Within "modules.php" from your module no stub for provider is included!

**Comment by virtualstep** [comment]
'stubs' => [
        'enabled' => false,
        'path' => base_path() . '/vendor/pingpong/modules/src/Pingpong/Modules/Commands/stubs',
        'files' => [
            'start' => 'start.php',
            'routes' => 'Http/routes.php',
            'json' => 'module.json',
            'views/index' => 'Resources/views/index.blade.php',
            'views/master' => 'Resources/views/layouts/master.blade.php',
            'scaffold/config' => 'Config/config.php',
            'composer' => 'composer.json',
<<< MISSING PROVIDER STUB >>>
        ],
        'replacements' => [
            'start' => ['LOWER_NAME'],
            'routes' => ['LOWER_NAME', 'STUDLY_NAME', 'MODULE_NAMESPACE'],
            'json' => ['LOWER_NAME', 'STUDLY_NAME', 'MODULE_NAMESPACE'],
            'views/index' => ['LOWER_NAME'],
            'views/master' => ['STUDLY_NAME'],
            'scaffold/config' => ['STUDLY_NAME'],
            'composer' => [
                'LOWER_NAME',
                'STUDLY_NAME',
                'VENDOR',
                'AUTHOR_NAME',
                'AUTHOR_EMAIL',
                'MODULE_NAMESPACE'
            ],
        ],
    ],

**Comment by gravitano** [comment]
Now controller, seed & views are not created when you creating a new module. If you want to add that, add `---resources` flag to `module:make` command.

```shell
php artisan module:make foo --resources
# OR
php artisan module:make foo -r
```

**Comment by virtualstep** [comment]
This i missing in your documentation!!!

**Comment by gravitano** [comment]
I am sorry, I haven't added it yet. Will add it soon.

**Comment by virtualstep** [comment]
Okay thanks. Now all is functional! Thanks for help!
