### ISSUE TITLE
You can use with the 5.1 -dev version?

### ISSUE THREAD

**Issue by marcelodelta** [pingpong-labs/modules#137]
You can use with the 5.1-dev version?

**Comment by gravitano** [comment]
Let me try.

**Comment by marcelodelta** [comment]
You get it?

**Comment by gravitano** [comment]
Not yet. Yesterday I try installing Laravel 5.1-dev, there is an error in Laravel. Will try it today. And let you know.

**Comment by gravitano** [comment]
I've been tested this package with Laravel 5.1. But, currently this package is not supported for Laravel 5.1-dev version. Maybe after this package released, I would add support for Laravel 5.1. Thanks

**Comment by marcelodelta** [comment]
Perfect . I'll be waiting. Thanks

**Comment by nWidart** [comment]
Out of curiosity, what specially failed ? I didn't know 5.1 had breaking changes.

**Comment by marcelodelta** [comment]
Hello Nicolas. An error in the package installation , stating that is not compatible with 5.1 -dev version.

**Comment by nWidart** [comment]
Oh, only that. That's because the requirement here is fixed to 5.0: https://github.com/pingpong-labs/modules/blob/2.0/composer.json#L20
The fix would just be to use `~5.0` instead, or even better `^5.0`.

**Comment by marcelodelta** [comment]
Version 5.1 is now already launched in May, then it would be the relevant modules have already supported .
I'm testing new features of 5.1.
For example the new broadcast system.

**Comment by nWidart** [comment]
Yeah same here. I'd really like to use 5.1 as quickly as possible for that feature alone.
