### ISSUE TITLE
Change config path for vendor:publish

### ISSUE THREAD

**Issue by virtualstep** [pingpong-labs/modules#139]
Hello,

how can I change the path for the "vendor:publish" command?

Currently all configs directly published in config-folder. My target is a subfolder, e.g. config/modules/

Greetings.

**Comment by nWidart** [comment]
You set the `publishedTo` method, to choose where to publish. More on this here: http://laravel.com/docs/5.0/packages#publishing-file-groups

**Comment by virtualstep** [comment]
Thanks.
