### ISSUE TITLE
Route Annotations

### ISSUE THREAD

**Issue by virtualstep** [pingpong-labs/modules#141]
Hello,

how can I use Route Annotations within modules ?

I build in my annotations definition e.g.

/**
     * Show the application login form.
     * @Get("login", as="login.login")
     * @return \Illuminate\Http\Response
     */

RouterServiceConfig is generated and included in module.json. Addional I added the Controller to the AnnoationsServiceProvider.

But after route:scan, route:clear I don't see the route within route:list

Is here a bug or a human error ?

Greetings

**Comment by gravitano** [comment]
I haven't try that feature with this package. I'll try it tonight and let you know the result.

**Comment by virtualstep** [comment]
Thanks a lot.

It's very important for us, that this is functional.

**Comment by gravitano** [comment]
Hi @virtualstep,

Here is an example of route annotations within `pingpong/modules`. https://github.com/pingpongcms/core/commit/cd78c56a95a480ccd743784a9a906b3847f0a7ba

**Comment by gravitano** [comment]
I think we can close this issue. Because, now, you have an example how to use route annotation in pingpong/modules. If you have other problem related to this issue, you can re-open this issue. Thank you :)
