### ISSUE TITLE
Auto Update Assets

### ISSUE THREAD

**Issue by iagomelanias** [pingpong-labs/modules#142]
Is there any way to publish the module assets automatically when they're changed (as a symlinks)? Run `module:publish` every time i change a file is really boring.

Thank you.

**Comment by gravitano** [comment]
You can create an elixir extension to allow that, maybe.

**Comment by nWidart** [comment]
That's indeed possible @iagomelanias .

I have something similar to run `stylist:publish`:

``` js
var gulp = require("gulp");
var shell = require('gulp-shell');
var elixir = require("laravel-elixir");

elixir.extend("stylistPublish", function() {
    gulp.task("stylistPublish", function() {
        gulp.src("").pipe(shell("php ../../artisan stylist:publish"));
    });
    return this.queueTask("stylistPublish");
});
```
