### ISSUE TITLE
Submodules Support

### ISSUE THREAD

**Issue by iagomelanias** [pingpong-labs/modules#143]
Will have any support to submodules in the future? Example: submodule Post for Blog, or submodule User for Panel. It's great for project organization, as Symfony does.

Thank you.

**Comment by gravitano** [comment]
Yes, of course. Submodules is a nice feature to organize the project. But, currently, I still find references to create a flexible submodules system. For now, you just need to use the composer to allow it.

**Comment by nWidart** [comment]
Submodules are a pain to manage, I'd use subtrees. But even that is not fun to manage, better then submodules though. 
Look it up on google, everyone will advise you to use subtrees.
