### ISSUE TITLE
module:migrate-*

### ISSUE THREAD

**Issue by xLink** [pingpong-labs/modules#148]
This set of commands just don't seem to work, `reset` & `rollback` give me cant find one of the migration classes

and `refresh` throw an error about cant find `../storage/app/modules/modules.used`

**Comment by gravitano** [comment]
Try publish the migration files to your `database/migrations` path and run `php artisan migrate` or `php artisan migrate:rollback` as usual.

**Comment by xLink** [comment]
hrm, that seemd to have worked, had to fix a path in the main config though

**Comment by luizmsilva** [comment]
Hello I am tentnado create seed for a specific module more feature coffee this error
[Illuminate\Contracts\Filesystem\FileNotFoundException]                       
File does not exist at path /var/www/hibrid/storage/app/modules/modules.used

**Comment by netconception** [comment]
Hey,

use command module:use <name> before seed generation or attach module name 
at the end of seed command (php artisan module:make-seed Test <ModuleName>

Greetings from Germany


Am 16. Juni 2015 22:54:46 schrieb Luiz Martins Silva 
<notifications@github.com>:

**Comment by xtsolucoes** [comment]
Thanks
