### ISSUE TITLE
cant install pingpong modules,, error in dependences

### ISSUE THREAD

**Issue by abdullah-abunada** [pingpong-labs/modules#149]
I cant install pingpong modules for laravel 5 because  error in dependence's specially in 
requires pingpong/generators 2.0.*@dev -> no matching package found.

**Comment by aitiba** [comment]
Add "pingpong/generators": "2.0.*@dev" to composer.json too.

**Comment by abdullah-abunada** [comment]
thank you, it is worked  ^_^
