### ISSUE TITLE
module ServiceProvider class not found

### ISSUE THREAD

**Issue by abdullah-abunada** [pingpong-labs/modules#150]
Hi every one,

after creating modules i faced this problem,
FatalErrorException in compiled.php line 1450:
Class 'Modules\Blog\Providers\BlogServiceProvider' not found

can you help me?

**Comment by gravitano** [comment]
Have you load that module using `PSR-4` ?

**Comment by abdullah-abunada** [comment]
Hi gravitano,
I already loaded it, I fixed this problem by deleting vendor/compiled.php 
thank you for replay,

**Comment by adangbryen** [comment]
FatalErrorException in ProviderRepository.php line 150:
Class 'Modules\Blog\Providers\BlogServiceProvider.php' not found

I met the same error.
I used your admin package first and then I composer your modules package 

    php artisan module:make Blog     
then I got the error above.

**Comment by gravitano** [comment]
Have you added new `Pingpong\Modules\Providers\BootstrapServiceProvider` class to your `providers` array in your config file ?

**Comment by adangbryen** [comment]
closed :)
Forgot to ran composer dump-autoload
thanks for your reply.

**Comment by ve3** [comment]
I can't fix this. Help?

Installed modules for Laravel.
Run `php artisan module:make Blog`
Run `php artisan module:list`

Error!!!!

**Comment by anhnhoktvn** [comment]
@ve3 , try loading your module using PSR-4:
//file: composer.json
"psr-4": {
            "App\\": "app/",
            "Modules\\": "modules/"
        }

then run `compser dump-autoload`
