### ISSUE TITLE
Facade Support

### ISSUE THREAD

**Issue by virtualstep** [pingpong-labs/modules#152]
Hi,

within the module.json file I can set providers.

But how can I set Facade-Aliases ?

I don't want to add some facades to the customer app config file.

Do u know what I mean?

**Comment by gravitano** [comment]
You can set aliases for any php class into `aliases` key in your `module.json` file. Please see this example https://github.com/pingpongcms/core/blob/master/module.json#L16-L18

**Comment by virtualstep** [comment]
Thanks!
