### ISSUE TITLE
modules not loaded

### ISSUE THREAD

**Issue by nWidart** [pingpong-labs/modules#154]
I ran a composer update with `"pingpong/modules": "2.0.*@dev",` in my composer.json file. 

But now no modules are getting loaded.

Did anything change ?

**Comment by gravitano** [comment]
Maybe you forgot add `Pingpong\Modules\Providers\BootstrapServiceProvider` to your config ? Or there is a syntax error in your `module.json` file ?

**Comment by nWidart** [comment]
Oh yeah! Forgot that one! :smiley:  

Thanks.
