### ISSUE TITLE
How about copy Resources to resources/modulename ?

### ISSUE THREAD

**Issue by Andrewwojownik** [pingpong-labs/modules#156]
Hello,

I know in modules Resources have lang and views directories, but on main resources have assets for example less files.
Is any config to add copy resource assets from modules to resources in use modules:publish (also if copy elixir config for gulp is helpful more ) ?

**Comment by gravitano** [comment]
You can publish the assets using `publishes` method in your module's service provider

```php
// on boot method
$this->publishes([
    __DIR__.'/../Assets/less' => base_path('/resources/assets/less')
], 'less')
```

**Comment by Andrewwojownik** [comment]
Works great, thanks :)
