### ISSUE TITLE
Artisan-Command "make-controller" with subfolder support

### ISSUE THREAD

**Issue by netconception** [pingpong-labs/modules#157]
Hi @gravitano,

new nickname, but same as every day: I have a question to you and I hope, you are not angry :)

Within my module structure I have currently subfolder in using. For example:

Modules > [modulename] > Http > Controllers > [category|subfolder] > Controller.php

With your artisan command I try to say: php artisan module:make-controller subfolder\controller but this has no effect.

Is this function build in or you need to add this ?

Greetings,

Heiko

**Comment by gravitano** [comment]
Will add this support for next release. Thank for the feedback :)

**Comment by netconception** [comment]
Hi @gravitano,

I'm very lucky to hear that. I wait for your update.

Greetings from Germany.
