### ISSUE TITLE
Error in Laravel 5 working modules and generators together

### ISSUE THREAD

**Issue by romannebesnuy** [pingpong-labs/modules#158]
I installed modules and generators together.
Modules work fine.

But when I call generator command its show error in console:

[ErrorException]
file_get_contents(...localhost\vendor\pingpong\modules\Commands/stubs...localhost\vendor\pingpong\generators\Stubs\model.stub): failed to open stream: Invalid argument

And when I commented Modules Service providers in config\app.php generators work ok =(

**Comment by romannebesnuy** [comment]
I understand problem.

ModuleServiceProvider on 48 line call
```php
Stub::setBasePath(__DIR__ . '/Commands/stubs');
```

and Generator when call render() function call in vendor\pingpong\generators\Stub.php

```php
public function getPath()
{
    return static::$basePath . $this->path;
}
```

But previous Module replace $basePath. So that they work together I replace
```php
return static::$basePath . $this->path; 
```
to
```php
return $this->path;
```


Or more short=) :
in vendor\pingpong\generators\Stub.php line 70 replace to this
```php
public function getPath()
{
    return $this->path;
}
```

**Comment by gravitano** [comment]
I will fix this issue soon :) Thank your for the feedback.

**Comment by gravitano** [comment]
I just fixed this issue with this commit https://github.com/pingpong-labs/sky/commit/db500fc7b9f38d371d25c97e39447fb49614e703. Also modules & generators packages have been tagged to new version 2.0.6. Run `composer update` and let me know if you still get the error of this issue.

**Comment by romannebesnuy** [comment]
Test with Modules 2.0.6 and Generators 2.0.6 together.
All works fine. Thanks
