### ISSUE TITLE
Load assets not specified protocol

### ISSUE THREAD

**Issue by nWidart** [pingpong-labs/modules#160]
Hello,

Could you please load assets without specifying `http://`, for instance:

Example:
``` php
Module::asset(''core:js/keypressAction.js)
```

Don't load:
```
<script src="http://asgardcms.dev/modules/core/js/keypressAction.js" type="text/javascript"></script>
```

but:

```
<script src="//asgardcms.dev/modules/core/js/keypressAction.js" type="text/javascript"></script>
```

This will load the asset to the current protocol, either http **or** https.

You could also provide an optional argument, in addition to loading assets over `//`, to set secure `true` or `false`.

Thanks!

(This is pretty important since loading the site over https will fail because of this issue)

**Comment by nWidart** [comment]
I just saw there is a `secure = false` argument to the `Asset::` helper.
Maybe there's a way of making this `//` by default. 
I know https://github.com/floatingpointsoftware/stylist does this, their assets are loading using `//asset/asset.css`

**Comment by nWidart** [comment]
I updated the package, using `"pingpong/modules": "~2.0",` , instead of the previous `@dev` one.

After update, I'm getting: 

```
[Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Pingpong\Support\Stub' not found                  
```

**Comment by nWidart** [comment]
When I try to go back to the `@dev` version, I getting

```
Nothing to install or update
Writing lock file
Generating autoload files
```
Plus the error mentioned above.

**Comment by gravitano** [comment]
Which version are you use ?

**Comment by nWidart** [comment]
`~2.0`

**Comment by gravitano** [comment]
Hmm.. Make sure get version `2.0.7` (the latest version). You can see in version `2.0.7` I've added `pingpong/support` to the `require` block https://github.com/pingpong-labs/modules/blob/2.0.7/composer.json#L22.

**Comment by nWidart** [comment]
I am on version `2.0.7`... 

![screen shot 2015-05-22 at 8 23 35 am](https://cloud.githubusercontent.com/assets/882397/7765261/1b9d6864-005c-11e5-9f87-8432ade27af9.png)


I just removed the `vendor` folder, to be sure nothing is in cache, ran a new `composer update`, and I'm still getting this error.

When looking at the `ModulesServiceProvider`, `Pingpong\Support\Stub` does not exist.

**Comment by nWidart** [comment]
Also, when I check pingpong/support, I don't see that `Stub` class.

**Comment by nWidart** [comment]
I see version `2.0.3` of pingpong/support is installed.

**Comment by nWidart** [comment]
I now manually added `"pingpong/support": "~2.0",` to the main `composer.json` file, so that it's gets the `2.0.6` version, and that seems to work.

But I shouldn't have to add it myself though.

**Comment by nWidart** [comment]
Using `2.0.*@dev` I cannot seem to get your change of today though, concernant the `//` protocol of assets.

**Comment by gravitano** [comment]
Just tagged this package to new version `2.0.8`. Try upgrade.

**Comment by nWidart** [comment]
okay thanks. Do I still need to explicitly specify `"pingpong/support": "~2.0",` in my composer.json file ?

**Comment by gravitano** [comment]
No. `pingpong/support` has been included (require) by `pingpong/modules` package.

**Comment by nWidart** [comment]
Okay, I removed `pingpong/support` from vendor folder to be sure it's included, though I still get

```
 [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Pingpong\Support\Stub' not found 
```
