### ISSUE TITLE
composer.json required vendor configs not published

### ISSUE THREAD

**Issue by netconception** [pingpong-labs/modules#162]
Hello,

I have for example the following composer.json within module folder

[...]
"require": {
        "pingpong/trusty": "~2.0"
    },
[...]

After execution of composer update the install of this require package is finished.

Now I execute the command "php artisan module:publish"...

But now the config file from trusty isn't published.

Can u correct this ?

module.json:

"providers": [
        "Pingpong\\Trusty\\TrustyServiceProvider"
    ],
    "aliases": {
        "Trusty": "Pingpong\\Trusty\\Facades\\Trusty",
        "Role": "Pingpong\\Trusty\\Role",
        "Permission": "Pingpong\\Trusty\\Permission"
    },

Greetings.

**Comment by nWidart** [comment]
Module:publish is only used to publish module assets.

You need to use laravel's `publishes` method to publish config/views etc.

**Comment by netconception** [comment]
Was my error!
