### ISSUE TITLE
Request: add "messages" - function to request stub

### ISSUE THREAD

**Issue by netconception** [pingpong-labs/modules#163]
Hi everbody,

in my local development I add the function "messages()" to the request.stub.

Why ?

With this function I can set custom error messages and I don't want to set this in every new form request.

Do u want to add this to your main repo ?

Code:

http://pastebin.com/ASrpe9CX

Greetings!

**Comment by netconception** [comment]
New link:

http://pastebin.com/ebDb3h6T

Addional add "attributes" function for nice names!

**Comment by nWidart** [comment]
Don't think this should be there by default, you can just add it yourself if needed. 

Otherwise bij the same login, `attributes` method should be there too, and basically every public method from the base `FormRequest` class that can be overwritten in your form request.
