### ISSUE TITLE
Error Pages

### ISSUE THREAD

**Issue by netconception** [pingpong-labs/modules#165]
Hello,

within Laravel all error pages located within "resource/views/errors".

It is possible, to set error files for e.g. 404 into the module folder ? Example within core module ?

Do you know what I mean ?

**Comment by nWidart** [comment]
It's possible yes. You just have to point laravel to your custom error pages inside the core module with an error gets thrown.

**Comment by netconception** [comment]
But I don't want to touch the default laravel application. Can I do this ?

**Comment by netconception** [comment]
Close because no answer.

**Comment by noxify** [comment]
what is with this: http://laravel.com/docs/5.1/errors#http-exceptions
