### ISSUE TITLE
translation files no more detected

### ISSUE THREAD

**Issue by nWidart** [pingpong-labs/modules#167]
After updating to version 2.0.10, no translations can be found anymore...

![screen shot 2015-06-05 at 5 27 13 pm](https://cloud.githubusercontent.com/assets/882397/8009336/81101d98-0ba8-11e5-92ad-bf0d543b64c1.png)

**Comment by nWidart** [comment]
Could you please make a new command for assets publishing and language publishing ? As this is very annoying to do!

![screen shot 2015-06-05 at 5 33 08 pm](https://cloud.githubusercontent.com/assets/882397/8009435/0c64e860-0ba9-11e5-86cc-dcdf41c4d52f.png)

**Comment by nWidart** [comment]
Also, once published it works, but it should fall back to the default language location if not found in published folder.
This is introducing a breaking change on a patch release!! 

I've said this again, but please please, consider following http://semver.org/ !

**Comment by gravitano** [comment]
Sorry, I haven't update the doc. I'm little busy. You can skip the question by adding `--force` flag.

**Comment by nWidart** [comment]
Okay.. but why not make them separate ? What if I want only to publish assets and not language files ?
There is already a separate migration publisher, it makes more sense to separate these too. :(

**Comment by gravitano** [comment]
Okay, will separate the command in next release.

**Comment by nWidart** [comment]
Please also make the translations work if they aren't publishing (this is another breaking change, introduced in a patch release)

**Comment by gravitano** [comment]
Yes, of course.

**Comment by nWidart** [comment]
Hope you tag this soon :)

**Comment by nWidart** [comment]
Oh you did, trying it out now.

**Comment by nWidart** [comment]
Seems to work fine. :smile: 

On thing I have since the update of earlier (>2.0.8), is a migation error:
```
Class 'CreateSettingTranslationsTable' not found  
```
But never had this before this update ... Also this migration has already run, and is already in the `migrations` table.
