### ISSUE TITLE
module:migrate-rollback not working

### ISSUE THREAD

**Issue by nWidart** [pingpong-labs/modules#170]
This still doesn't work.

```
nicolaswidart@Nicolass-MacBook-Pro ~/Sites/Testing/asgard-test (develop)$ art module:migrate-rollback media
Nothing to rollback.
```

**Comment by nWidart** [comment]
Correction, it only can rollback the module which has the last migration in the `migrations` table

**Comment by gravitano** [comment]
Yes, of course. Rollback only for last migration. If you want to reset all migration from specific module, use `module:migrate-reset` instead.

**Comment by nWidart** [comment]
Well in that case the old rollback command worked fine!

I thought  you made something custom to allow for this, because it is possible, just got to do it the manual way (since you already copied the Migrator class).

**Comment by gravitano** [comment]
Old rollback command is using `migrate:rollback` command from Laravel. And it will rollback all migration that the last from the migrations table. This is not what we want for rollback-ing module's migrations.

**Comment by nWidart** [comment]
I see, I was probably lucky then. :)

Also, it is possible to make it work on a module per module basis. By
checking the module's migration, and calling the down method for the last
one(s) (in same batch) and remiving it from migrations table.

On Sunday, June 7, 2015, Gravitano <notifications@github.com> wrote:

> Old rollback command is using migrate:rollback command from Laravel. And
> it will rollback all migration that the last from the migrations table.
> This is not what we want for rollback-ing module's migrations.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pingpong-labs/modules/issues/170#issuecomment-109693281>
> .
>


-- 


Nicolas Widart
www.nicolaswidart.com
