### ISSUE TITLE
Class 'Laracasts\Flash\FlashServiceProvider' not found

### ISSUE THREAD

**Issue by adis-me** [pingpong-labs/modules#173]
Hi,

I am encountering issues when trying to the Flash package from Laracasts into a module.

My `modules.json` looks like this:

```
{
    "name": "ModulaCore",
    "alias": "modulacore",
    "description": "",
    "keywords": [],
    "active": 1,
    "order": 10,
    "providers": [
        "Modules\\ModulaCore\\Providers\\ModulaCoreServiceProvider",
        "Modules\\ModulaCore\\Providers\\RepositoryServiceProvider",
        "Laracasts\\Flash\\FlashServiceProvider"
    ],
    "aliases":{},
    "files": [
        "start.php"
    ]
}
```

And my `composer.json` looks like:

```
{
  "name": "pingpong-modules/modulacore",
  "description": "",
  "authors": [
    {
      "name": "Pingpong Labs",
      "email": "pingpong.labs@gmail.com"
    }
  ],
  "require": {
    "laracasts/flash": "~1.3"
  },
  "autoload": {
    "psr-4": {
      "Modules\\ModulaCore\\": ""
    }
  }
}

```

I really do not know what is wrong here. Is it because `laracasts/flash` is a *psr-0* package?

**Comment by gravitano** [comment]
You need to add `laracasts/flash` manually to your laravel's `composer.json` file and run `composer update`.

You can also add new `require` key to your `module.json` file and run `php artisan module:update` to pull in the package.

**Comment by adis-me** [comment]
With your first suggestion, do you main the main project's `composer.json` or the `composer.json` in my Module?

**Comment by netconception** [comment]
Hi @adis-me,

add this require within your module.json file in your module.

Greetings

**Comment by adis-me** [comment]
Rgarding the second suggestion:
@netconception @gravitano Adding the require and the FlashServiceProvider (after module:dump) in the module.json works! But in that case my main projects `composer.json` is updated and not the `composer.json` of the module..

This is not working when copying the whole module to another project. There I get the same error, because the dependency is not added to my module but to the main project.

This would also happen to other people installing my modules, right? They cannot install it unless the remove the FlashServiceProvider from the `modules.json` run `php artisan module:update` and then place it back?

**Comment by adis-me** [comment]
If someone has time to review, here the project: https://github.com/adis-me/ModulaCore

**Comment by netconception** [comment]
Hi @adis-me,

I use required packages in two ways

1.) In my development I add the required packages within the module composer.json file. Within the main composer file I add `wikimedia/composer-merge-plugin` and set an extra option to main composer file.

2.) My customers get all modules via git. So all required packages from module composer.json installed automatically.

I hope this is helpful for you!

**Comment by adis-me** [comment]
@netconception ok, thanks for your explanation.
