### ISSUE TITLE
Vendor Publishing: Views in Base Path not in Resource-Path

### ISSUE THREAD

**Issue by netconception** [pingpong-labs/modules#174]
Hi @gravitano,

when I execute vendor:publish all files published into the base path with subdir "views".

That's okay, but when I need to copy vendor views the must be place within resource/vendor.

So can I publish the views from modules within resource/views?

**Comment by gravitano** [comment]
You can edit the view path as you want in your module's service provider file. Please see this stub https://github.com/pingpong-labs/modules/blob/master/Commands/stubs/scaffold/provider.stub#L56-L66.

**Comment by netconception** [comment]
Thanks!
