### ISSUE TITLE
Fatal Error: Pingpong\Generators\Exceptions\InvalidMigrationNameException

### ISSUE THREAD

**Issue by netconception** [pingpong-labs/modules#177]
Hello @gravitano,

I want to generate a migration for my module (I use L5.1).

First I type in the command

     php artisan module:use Content

After that I want to execute

     php artisan module:make-migration create_content_table

But then I get an error:

     [Symfony\Component\Debug\Exception\FatalErrorException]
     Class 'Pingpong\Generators\Exceptions\InvalidMigrationNameException' not found

Can u help me ?

Thanks and greetings from Germany

Heiko

**Comment by gravitano** [comment]
Hmm, looks like your migration name is invalid.

**Comment by netconception** [comment]
Hi @gravitano,

why It is invalid ? My migration name is

     create_content_table

Before update to laravel 5.1 all was okay.

**Comment by gravitano** [comment]
Hmm, you are using version `2.1.*@dev` ? I think there are some conflict with new Laravel 5.1 signature command. I would try find solution for this problem.

**Comment by netconception** [comment]
Hi @gravitano,

yes. I use version `2.1.@dev`.

I hope u find a solution!

I stay tuned.

**Comment by gravitano** [comment]
After debugging and trying this package with fresh L5.1. I dont see error with naming convention of migration, just class `Pingpong\Generators\Exceptions\InvalidMigrationNameException` really does not exist. Also, I try create dummy module and migration named `create_content_table` and all works fine.

**Comment by netconception** [comment]
Hi

I have addionally the modules folder within app and the app Name is changend

I have this error and in Laravel 5 with the same config no error.
 



Am 18. Juni 2015 18:10:26 schrieb Gravitano <notifications@github.com>:

**Comment by netconception** [comment]
Hi @gravitano,

I don't know but this morning I type the same commands in and all works okay.

That's strange!

**Comment by praveesh4u** [comment]
Please makes sure that when you create a migration, the migration name starts with 
any of the following words. 

            'create',
            'make',
            'delete',
            'remove',

            'add',
            'update',
            'append',
            'insert',
            'destroy',
            'drop',

An 'InvalidMigrationException' was obeserved otherwise(Don't know wheather it is a global phenomenon)

**Comment by spartangian** [comment]
@praveesh4u this solves the issue. thank you
