### ISSUE TITLE
Updating to 2.0.18: class cache not found

### ISSUE THREAD

**Issue by nWidart** [pingpong-labs/modules#180]
Hello,

Updating to `2.0.18`, is giving me this error: `class cache not found`.
I already registered my language and view namespaces in the Service Provider.

I had to move the registration to the boot method to remove the `class translator not found` error. https://github.com/AsgardCms/Core/blob/develop/Providers/CoreServiceProvider.php#L179

By apparently something needs to the cache, any idea what / how to resolve ?

Thanks

**Comment by nWidart** [comment]
If I put the `$this->app['modules']->register();` method call back on the `boot()` method, then it works.

But then the language files in `resources/lang/modules` aren't getting read.
For instance for a user module:

`resources/lang/modules/user/en/users.php`

**Comment by nWidart** [comment]
Alright, I managed to fix it by

1. Move the module registering back into `boot()` method
2. Using:

    ```
$moduleName = $module->getName();

        $langPath = base_path("resources/lang/modules/$moduleName");

        if (is_dir($langPath)) {
            $this->loadTranslationsFrom($langPath, $moduleName);
        } else {
            $this->loadTranslationsFrom($module->getPath() . '/Resources/lang', $moduleName);
        }
    ```

**Comment by gravitano** [comment]
Sorry for my late response. Thank for the feedback. I would update and fix this issue.

**Comment by nWidart** [comment]
It had to be in the register method after all.

**Comment by gravitano** [comment]
Hmm. Do you still register your module's lang namespace in `start.php` file? I recommend you put it in `boot` method in module's service provider class.

**Comment by nWidart** [comment]
No, like I said above, I always had in the service provider, and never in start.php. 
https://github.com/AsgardCms/Core/blob/develop/Providers/CoreServiceProvider.php#L211
