### ISSUE TITLE
Accessing translation files

### ISSUE THREAD

**Issue by nicozimmermann94** [pingpong-labs/modules#181]
Hello!
How does one access a translations file from a module?
I have a module calles `Vpns` with the translation file `help.php`. I try to access the data with `trans('vpns.help.new.name')` but it will not work.
The translation file looks like this:
`'help' => [
        'new' => [
            'name' => 'Hilftetext für Name'
        ]
    ]`

**Comment by gravitano** [comment]
You can access the translation value like this:
```php
trans('vpns::help.new.name');
```

**Comment by nicozimmermann94** [comment]
That does not work either.

**Comment by gravitano** [comment]
Do you put the `help.php` file in locale folder? For example, if in your locale is `en`, you need to push that in `Resources/lang/en` folder.

**Comment by nicozimmermann94** [comment]
Yes I created the file inside of my `de` folder.
The full path is: `\modules\Vpns\Resources\lang\de\help.php`

**Comment by gravitano** [comment]
Is your app locale `de` ?

Sel, 23 Jun 2015 pukul 21.42 nicozimmermann94 <notifications@github.com>
menulis:

**Comment by nicozimmermann94** [comment]
Yes.
It works when I place the same file in the default lavaravel lang folder.
Am 23.06.2015 17:01 schrieb Gravitano <notifications@github.com>:Is your app locale `de` ?

Sel, 23 Jun 2015 pukul 21.42 nicozimmermann94 <notifications@github.com>
menulis:

**Comment by nicozimmermann94** [comment]
Did you find something? :)

**Comment by yazfield** [comment]
same problem here, \modules\moduleName\resources\lang\en\global.php
published to \resources\lang\moduleName\en\global.php

when i use either ``` trans('moduleName.global.somekey') ``` or ``` trans('moduleName::blobal.somekey') ``` it doesn't work, i have to put it manually in default laravel folder ``` \resources\lang\en\moduleName\global.php ``` and access it using ``` trans('moduleName.global.somekey') ```

any solution?

**Comment by nicozimmermann94** [comment]
@gravitano I don not want to annoy you but this problem is kind of important for my project. Maybe you can give a hint for what I have to look for?

**Comment by yazfield** [comment]
@nicozimmermann94 have you published the translation files? it worked for me, use ``` php artisan module:publish-translation moduleName ```

**Comment by gravitano** [comment]
@nicozimmermann94 : you can put your translation file in your `Resources/lang` folder and make sure you put the translation file into locale folder. For example, if you have module called `foo`, your locale is `de` and translation file named `bar`, the translation path is `modules/Foo/Resources/lang/de/bar.php`. To access the key from the `bar` file, you can do something like this:
```php
Lang::get('bar::key');

trans('bar::key');
```
Tell me if the instruction above does not work.

**Comment by mspiderv** [comment]
I find the solution.

If locale is {locale}, translation file name is {file} and module name is {module} then the  translation path is modules/{module}/Resources/lang/{locale}/{file}.php

In modules/{module}/Providers/{module}ServiceProvider.php find method registerTranslations(). There should be this:

$langPath = base_path('resources/lang/modules/{module}');

if (is_dir($langPath)) {
	$this->loadTranslationsFrom($langPath, '{module}');
} else {
	$this->loadTranslationsFrom(__DIR__ .'/../Resources/lang', '{module}');
}

Dont remember call $this->registerTranslations() in boot() at 20th row in the provider file.

Then you can easily access your lang values by trans("{module}::{file}.{key}"); where {key} in the key in lang file.

I think this one should be closed.

**Comment by nicozimmermann94** [comment]
@gravitano @mspiderv 
Unfortunately, nothing works. The good news: after `composer update` I can confirm that the language file gets loaded (did a dd() in the lang file, it did not work before the update!). The bad news: I do not know how to access the keys. The module is called vpns. My lang file (de/help.php) looks like this:
`return ['help' => ['new' => ['name' => 'Hilftetext für Name']]];`
I tried the following:
`{{ trans('vpns::help.new.name') }}`
`{{ trans('vpns::new.name') }}`
`{{ trans('help::new.name') }}`
`{{ trans('help::help.new.name') }}`
`{{ trans('help.new.name') }}`

**Comment by mspiderv** [comment]
@nicozimmermann94 Did you set up your ocale "de" in config/app.php ?

**Comment by nicozimmermann94** [comment]
@mspiderv Yes. The file also gets loaded.

**Comment by nicozimmermann94** [comment]
Found the problem:
Instead of using `{{ trans('vpns::help.new.name') }}` I had to use `{{ trans('vpns::help.help.new.name') }}`
