### ISSUE TITLE
Cannot run module:seed

### ISSUE THREAD

**Issue by joshbrw** [pingpong-labs/modules#189]
When trying to run `module:seed` without any arguments I get the following error:

```
[Illuminate\Contracts\Filesystem\FileNotFoundException]
File does not exist at path /storage/app/modules/modules.used
```

If I then manually create that file and give it the correct permissions I get the following error:

```
[Pingpong\Modules\Exceptions\ModuleNotFoundException]
Module [] does not exist!
```

**Comment by gravitano** [comment]
Currently, you can not seed from all modules, but you can seed from specific module. For example: `artisan module:seed foo`.

**Comment by nWidart** [comment]
Maybe display a descriptive error message in that case ?
