### ISSUE TITLE
How to proper include and use a composer dependency in a module?

### ISSUE THREAD

**Issue by mtisi** [pingpong-labs/modules#193]
Hi @gravitano,

I'm using your plugin to create a modulazired application.
However, I can't figure out how to use an external library, like intervention/image, in a module.
Here are the steps I took:

**Create a new application and install pingpong modules**

``` bash
$ laravel new testcore

Crafting application...
> php -r "copy('.env.example', '.env');"
> php artisan clear-compiled
> php artisan optimize
Generating optimized class loader
> php artisan key:generate
Application key [3J6WvdEcA2IpTtuo6jV87XGUbNO8xJ39] set successfully.
Application ready! Build something amazing.

$ cd testcore
$ composer require pingpong/modules

Using version ^2.1 for pingpong/modules
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing laravelcollective/html (v5.1.3)
    Loading from cache

  - Installing erusev/parsedown (1.5.3)
    Loading from cache

  - Installing erusev/parsedown-extra (0.7.0)
    Loading from cache

  - Installing pingpong/support (v2.1.4)
    Loading from cache

  - Installing doctrine/lexer (v1.0.1)
    Loading from cache

  - Installing doctrine/annotations (v1.2.6)
    Loading from cache

  - Installing doctrine/collections (v1.3.0)
    Loading from cache

  - Installing doctrine/cache (v1.4.1)
    Loading from cache

  - Installing doctrine/common (v2.5.0)
    Loading from cache

  - Installing doctrine/dbal (v2.5.1)
    Loading from cache

  - Installing pingpong/generators (v2.1.4)
    Loading from cache

  - Installing pingpong/modules (v2.1.4)
    Loading from cache

Writing lock file
Generating autoload files
> php artisan optimize
Generating optimized class loader
```
**Add Modules Service Provider and Alias to config/app.php**
``` php
    'providers' => [
        Pingpong\Modules\ModulesServiceProvider::class,
        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Foundation\Providers\ArtisanServiceProvider::class,
        ...
    ],
    'aliases' => [
        'Module'    => Pingpong\Modules\Facades\Module::class,
        'App'       => Illuminate\Support\Facades\App::class,
        ...
    ],
```
**Add PSR-4 loading of Modules namespace**
```json
{
  "autoload": {
    "psr-4": {
      "App\\": "app/",
      "Modules\\": "modules/"
    }
  }
}
```
```bash
$ composer dump-autoload
```
**Publish vendor files**
``` bash
$ php artisan vendor:publish

Copied File [/vendor/pingpong/modules/src/config/config.php] To [/config/modules.php]
Publishing complete for tag []!

$ php artisan module:setup
Modules directory created successfully
Assets directory created successfully
```
**Create a new module**
```bash
$ php artisan module:make Media
Created : /var/www/testcore/modules/Media/start.php
Created : /var/www/testcore/modules/Media/Http/routes.php
Created : /var/www/testcore/modules/Media/module.json
Created : /var/www/testcore/modules/Media/Resources/views/index.blade.php
Created : /var/www/testcore/modules/Media/Resources/views/layouts/master.blade.php
Created : /var/www/testcore/modules/Media/Config/config.php
Created : /var/www/testcore/modules/Media/composer.json
Created : /var/www/testcore/modules/Media/Database/Seeders/MediaDatabaseSeeder.php
Created : /var/www/testcore/modules/Media/Providers/MediaServiceProvider.php
Created : /var/www/testcore/modules/Media/Http/Controllers/MediaController.php
Module [Media] created successfully.
```
Everything until this point works fine: i can browse to testcore.localhost/media and Laravel successfully shows me the module Welcome page.
Even the module status shows me that everything is ok:
```bash
php artisan module:list
+-------+---------+-------+---------------------------------+
| Name  | Status  | Order | Path                            |
+-------+---------+-------+---------------------------------+
| Media | Enabled | 0     | /var/www/testcore/modules/Media |
+-------+---------+-------+---------------------------------+
```
**Add composer dependency**
``` bash
$ cd modules/Media
$ composer require intervention/image
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing psr/http-message (1.0)
    Loading from cache

  - Installing guzzlehttp/psr7 (1.1.0)
    Loading from cache

  - Installing intervention/image (2.3.1)
    Loading from cache

intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
Writing lock file
Generating autoload files
```
Everything is fine again:
```bash
php artisan module:list
+-------+---------+-------+---------------------------------+
| Name  | Status  | Order | Path                            |
+-------+---------+-------+---------------------------------+
| Media | Enabled | 0     | /var/www/testcore/modules/Media |
+-------+---------+-------+---------------------------------+
```
But now i need to include the Intervention Service Provider to be able to use it, so i edit my module.json file like this:
``` json
{
    "name": "Media",
    "alias": "media",
    "description": "",
    "keywords": [],
    "active": 1,
    "order": 0,
    "providers": [
        "Modules\\Media\\Providers\\MediaServiceProvider",
        "Intervention\\Image\\ImageServiceProvider"
    ],
    "aliases":{},
    "files": [
        "start.php"
    ]
}
```

If I check again the modules statuses, artisan give me an error:

```bash
$ php artisan module:list
PHP Fatal error:  Class 'Intervention\Image\ImageServiceProvider' not found in /var/www/testcore/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 575
                                                             
  [Symfony\Component\Debug\Exception\FatalErrorException]    
  Class 'Intervention\Image\ImageServiceProvider' not found  
                                                             
```

I think that this is related to not including composer's autoload.php inside modules/Media/vendor/.

Are there any correct ways to do this?
I spotted a class named Starter inside pingpong/modules which seems to do exactly this, but I don't know how to use it.

Please help me!

**Comment by mtisi** [comment]
@nWidart you do this in every AsgardCMS's module. How can you do that?

**Comment by nWidart** [comment]
I use composer installers, but looks pretty much the same yes.
One problem though, composer installers, will only check the module's composer.json on *first install*. If you add a dependency later on, it won't get picked up by composer update.

**Comment by mtisi** [comment]
@nWidart thank you for your response! I can't rely on composer-installers because our project will not be open-sourced...
Will wait for an answer from @gravitano ...

**Comment by drtzack** [comment]
+1

**Comment by Ifnot** [comment]
Same here. I tried to add theses lines on the module composer.json :

    "config": {
       "vendor-dir": "../../vendor"
    },

It works well, but remove all dependencies of the laravel project from the main composer.json :D :santa:

**Comment by Ifnot** [comment]
This https://github.com/composer/composer/issues/183 is interesting for us, but opened since 2012 so ... i think there will no suport in days.

**Comment by noxify** [comment]
Hi,

Did you try this: https://github.com/wikimedia/composer-merge-plugin

And what if you're integrate your module as a composer package? This should also solve your problems :)

**Comment by Ifnot** [comment]
This is a private project, so ... i dont want to include a composer workflow into this one. It is just a way for me to make a clean architecture of a project.

I think we do not have to make module as composer packages with pingpong-labs/modules for using module composer dependancies. This should be lightweight as possible :)

I will try your solution, if it works i will explain my process here. Thanks !

**Comment by nWidart** [comment]
You can use Satis or Toran proxy to handle private packages. ( https://getcomposer.org/doc/05-repositories.md#hosting-your-own )

Also, with the latest composer version you can have local packages. ( https://getcomposer.org/doc/05-repositories.md#path)

**Comment by Ifnot** [comment]
Thanks for the link, i think there are many ways to handle this with all suggestions :)

@nWidart : I confirm that i doesnt want a composer package for each of my modules, it is just a architecture of an app, i cannot use a git per module etc ...

solution of @noxify works well ! :) Just add the package, set to merge the files from `modules/*/composer.json` and it works :)

**Comment by noxify** [comment]
perfect @Ifnot - good to know that it's working :) 

Then we can close this, or?

**Comment by Ifnot** [comment]
I think we can close this as implementation of https://github.com/wikimedia/composer-merge-plugin solves the problem.

First, install the package :

    composer require wikimedia/composer-merge-plugin

Next, require modules composer.json into your main project `composer.json` :

    "extra": {
        "merge-plugin": {
            "include": [
                "modules/*/composer.json"
            ]
        }
    }

And then, simply add dependancies into your modules `composer.json` as usual

**Comment by gabyrusu** [comment]
for me it doesn't seem to work. it doesn't install my dependencies from "modules/*/composer.json"

composer.json: 
.....
`"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "pingpong/modules": "~2.1",
        "wikimedia/composer-merge-plugin": "^1.3"
    },
    "extra": {
        "merge-plugin": {
            "require": [
                "modules/*/composer.json"
            ]
        }
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "2.8.*|3.0.*",
        "barryvdh/laravel-debugbar": "^2.1"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/",
            "Modules\\": "modules/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "dev",
    "prefer-stable": true`

modules/core/composer.json
.....
`"require": {
        "pingpong/modules": "~2.1",
        "teepluss/theme": "dev-master"
    },
    "autoload": {
        "psr-4": {
            "Modules\\Core\\": "."
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true`

any ideas??

thanks!

**Comment by spescina** [comment]
No luck with this setup. Anyone confirming that this approach should work?

**Comment by nWidart** [comment]
What are you trying to do ?

To include a dependency:

- If your module is a one-time use: require it globally,
- If you plan to re-use the module: require it globally and in the module folder.

It has to be both for the latter, because composer-installers doesn't check those composer.json files. It only does so when installing the project.

**Comment by spescina** [comment]
I'm planning to build reusable modules.
It's a bit tricky what you're suggesting but should work, let me try. I've also tried the merge plugin but couldn't get it to work...

Tnx

**Comment by nWidart** [comment]
It's not really tricky, you only need to add your dependency in 2 composer.json files, instead of one. That's it. 😄

**Comment by spescina** [comment]
Yeah but it's not an ideal workflow in my opinion... there's some caveats in it

**Comment by nWidart** [comment]
That's how composer work. I haven't had any issues with it, both for testing the modules & re-using them.

**Comment by spescina** [comment]
How are you dealing with modules global require in the main project and vcs? Do you leave them in it until modules are completed?

**Comment by nWidart** [comment]
You could either use the vcs composer type indeed, or via a submodule.

I would work on the module until it's done. Copy the module outside, init a git repository in it, push on a remote, add to packagist/satis/toranproxy, and require that module back into the project using vcs type so it can still be edited.

**Comment by redtusker** [comment]
How can i Vendor:publish in a module (having issue with modules)
