### ISSUE TITLE
Use pingpong/themes in modules

### ISSUE THREAD

**Issue by InnerCode** [pingpong-labs/modules#197]
Hi,

Is there a way to use pingpong/themes in pingpong/modules? The themes module have a separate folder which is outside of the resources/views folder.
So, how can I extend a theme view from a module view? For example @extend('path/to/theme/index')

Thanks in advance

**Comment by InnerCode** [comment]
Problem solved! :)
Adding the line `realpath(base_path('resources/themes'))` in the paths array in the file `app/config/view.php` did it.

**Comment by gravitano** [comment]
You can extend the theme's view like this:
```php
@extends('themename::the-view')
```

**Comment by InnerCode** [comment]
That's a nicer one!
Thanks @gravitano
