### ISSUE TITLE
How to create module inside app/?

### ISSUE THREAD

**Issue by mitulkoradiya** [pingpong-labs/modules#216]
Hi @gravitano,
I'm using your plugin to create a modular app inside laravel 5.1.

Currently module create inside  `project/modules/blog`, but i want to create that module folder inside app folder and structure like `project/app/modules/blog`.

So can you suggest me how can i do that.
Thanks

**Comment by noxify** [comment]
Hi,

you have to change the `composer.json`

From:
```
{
  "autoload": {
    "psr-4": {
      "App\\": "app/",
      "Modules\\": "modules/"
    }
  }
}
```

To:

```
{
  "autoload": {
    "psr-4": {
      "App\\": "app/",
      "Modules\\": "app/modules/"
    }
  }
}
```

**Comment by mitulkoradiya** [comment]
HI,

I got the solution, and the changes are


file `composer.json`
```
{
  "autoload": {
    "psr-4": {
      "App\\": "app/",
      "Modules\\": "app/modules/"
    }
  }
}
````

 
file `config\modules.php`
```
return [
    ...
    'namespace' => 'App\Modules',

    'paths' => [
        'modules' => base_path('App\modules'),
        'assets' => public_path('App\modules'),
        'migration' => base_path('App\database/migrations'),
     ...
    ],
    ...
];
```

May this is the right solution or not but i got he solution.
Thanks.
