### ISSUE TITLE
Documentation site not working

### ISSUE THREAD

**Issue by SergeyMiracle** [pingpong-labs/modules#228]
to work or not to work, this is a question...

**Comment by nWidart** [comment]
@gravitano any updates on this ?

**Comment by gravitano** [comment]
@SergeyMiracle @nWidart : I am still working on this and hopefully my site will back soon. Thanks!

**Comment by nWidart** [comment]
Awesome, thank you for the heads-up! :smile:

**Comment by gravitano** [comment]
Also, you can grab the docs here https://github.com/pingpong-labs/docs.

**Comment by SergeyMiracle** [comment]
Ok thx

**Comment by gravitano** [comment]
Finally, the site has been up and running!

**Comment by nWidart** [comment]
:tada: :balloon: :+1:
