### ISSUE TITLE
Laravel 5.2 support

### ISSUE THREAD

**Issue by moston** [pingpong-labs/modules#233]
Is there gonna be support to Laravel 5.2 which was released lately?

**Comment by timvanuum** [comment]
+1

**Comment by pavankumarkatakam** [comment]
+1

**Comment by Dronnikkl** [comment]
+1

**Comment by nWidart** [comment]
Did you guys even check the 2.2 branch before +1'ing ? it has support for 5.2 ...

**Comment by moston** [comment]
It showed up today but even with updating composer.json there is one thing:

PHP Fatal error:  Call to undefined method Illuminate\Foundation\Application::bindShared() in /vendor/pingpong/modules/ModulesServiceProvider.php on line 93

Because bindShared was deprecated in 5.1 and now in 5.2 the functiond doesn't even exist.

**Comment by nWidart** [comment]
Ah yes, in that case @gravitano needs to update that to `singleton()`, or you can send a PR. :smile:

**Comment by moston** [comment]
Made PR :+1:

**Comment by hobord** [comment]
I try run
composer require "pingpong/modules:2.2.x-dev"
But I got fail.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for pingpong/modules 2.2.x-dev -> satisfiable by pingpong/modules[2.2.x-dev].
    - pingpong/modules 2.2.x-dev requires pingpong/generators 2.2.*@dev -> no matching package found.

What I mistake?

**Comment by marcelodelta** [comment]
Hi, 

The modules will work in version 5.2 of Laravel ?

**Comment by marcelodelta** [comment]
"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "laravelcollective/html": "5.2.*",
        "pingpong/modules": "2.2.*@dev",
        "pingpong/generators": "2.2.*@dev",
        "pingpong/support": "2.2.*@dev"
    },

It's working!

**Comment by constant-null** [comment]
have the same problem as hobord 

config: 
"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "pingpong/modules": "2.2.*@dev"
}

error
Problem 1
    - Installation request for pingpong/modules 2.2.*@dev -> satisfiable by pingpong/modules[2.2.x-dev].
    - pingpong/modules 2.2.x-dev requires pingpong/generators 2.2.*@dev -> no matching package found.

**Comment by bdsoha** [comment]
Able to install properly but unable to run, having an issue with `bindShare()` as well.

**Comment by timvanuum** [comment]
@bdsoha replace that method with singleton

**Comment by BioPhoton** [comment]
+1
For 5.2

**Comment by mouhsinelonly** [comment]
+1

**Comment by saulommartins** [comment]
+1

**Comment by adrianolobo** [comment]
+1

**Comment by nWidart** [comment]
Doesn't it works since this commit https://github.com/pingpong-labs/modules/commit/fbed30d478a41e1599eb740d6d17ce09924bef1e ?

**Comment by saulommartins** [comment]
When i try to create a new module using this command: 
php artisan module:make FppTeste

Any other command like "php artisan list" give me this error:

                                                                        
  [Symfony\Component\Debug\Exception\FatalErrorException]               
  Class 'Modules\FppTeste\Providers\FppTesteServiceProvider' not found  

I added this class "Modules\FppTeste\Providers\FppTesteServiceProvider" to the providers without success. I think this is a Laravel 5.2 error, because it worked fine on Laravel 5.1.

![screen shot 2016-01-06 at 18 11 54](https://cloud.githubusercontent.com/assets/1260927/12153453/03c2e4cc-b4a1-11e5-9aa5-21fc269e6015.png)

**Comment by mouhsinelonly** [comment]
Trait 'Illuminate\Foundation\Bus\DispatchesCommands'  Is deprecated in laravel 5.2 , should use Trait 'Illuminate\Foundation\Bus\DispatchesJobs' not found in Pingpong\Modules\Routing\Controller.php

**Comment by ruelluna** [comment]
+1

**Comment by gravitano** [comment]
Hi everyone, 

First, I want to thank to everyone who exited and help me developing this package. Now, I am glad introduce you that `pingpong/modules` version `2.2.0` has been released which are contains full support for Laravel 5.2 and with some bug fixes.

To read full of release notes, you may visit this link bellow:
https://github.com/pingpong-labs/modules/releases/tag/v2.2.0

Thanks!

**Comment by mjunaid720** [comment]
today i configure it for laravel 5.2 it works fine. you can configure through this link . http://sky.pingpong-labs.com/docs/2.0/modules.
