### ISSUE TITLE
Support for Laravel 5.2?

### ISSUE THREAD

**Issue by tam5** [pingpong-labs/modules#248]
Is there going to be support for Laravel 5.2?

Right now I get the following error while trying to install PingPong 2.1:

```
Problem 1
    - pingpong/sky v2.1.5 requires laravel/framework 5.1.* -> no matching package found.
    - pingpong/sky v2.1.4 requires laravel/framework 5.1.* -> no matching package found.
    - pingpong/sky v2.1.3 requires laravel/framework 5.1.* -> no matching package found.
    - pingpong/sky v2.1.2 requires laravel/framework 5.1.* -> no matching package found.
    - pingpong/sky v2.1.1 requires laravel/framework 5.1.* -> no matching package found.
    - pingpong/sky v2.1.0 requires laravel/framework 5.1.* -> no matching package found.
    - Installation request for pingpong/sky ~2.1 -> satisfiable by pingpong/sky[v2.1.0, v2.1.1, v2.1.2, v2.1.3, v2.1.4, v2.1.5].
```

Upon further review it seems that there will be support for 5.2 as this repo has a 2.2 branch which requires Laravel 5.2.*, but this branch is not yet available through composer and does not yet have documentation.

**Comment by 42antoine** [comment]
:+1:

**Comment by c1t1zen** [comment]
hey i used this command and it worked with me for laravel 5.2

`` composer require "pingpong/modules:~2.2"`

**Comment by tam5** [comment]
ah yes you are correct thank you. i am able to get it working as well. I guess the docs just need an update now

**Comment by 42antoine** [comment]
The problem was found with pingpong/sky ~2.1 and not pingpong/modules: ~2.x. The complete package wasn't able to be installed on 5.2.
