### ISSUE TITLE
Website has been down for weeks.

### ISSUE THREAD

**Issue by JapSeyz** [pingpong-labs/modules#265]
I've been getting timeout errors for 2+ weeks now.

Any ETA on a fix? I'd like to look at the documentation.

**Comment by nWidart** [comment]
It is indeed annoying that the site has been down for a long time.

The docs however are also on github: https://github.com/pingpong-labs/docs/blob/2.2/modules.md

**Comment by JapSeyz** [comment]
@nWidart Thanks :)
