### ISSUE TITLE
403 Forbidden for the Official Docs

### ISSUE THREAD

**Issue by ghost** [pingpong-labs/modules#267]
I can't see the documentation for this package, it just redirects to a hosting provider with a 403.

Any chance this can be fixed please.

**Comment by nWidart** [comment]
Look at closed issues. Someone else had same issue.

**Comment by TrungVuAnt** [comment]
You can find the document here: https://github.com/pingpong-labs/docs

**Comment by gravitano** [comment]
https://pingpong-labs.github.io/docs/modules.html
