### ISSUE TITLE
Register ServiceProvider

### ISSUE THREAD

**Issue by billmn** [pingpong-labs/modules#47]
How can I register a module's ServiceProvider?
I haven't seen any reference about this in documentation.

Cheers

**Comment by ghprod** [comment]
@nWidart could you share your code in here? thanks

**Comment by nWidart** [comment]
This has been integrated into the package itself, you can simply have the `providers` key in you `module.json` file and it'll get loaded.

**Comment by noxify** [comment]
Hi @ghprod,

Here an example from my Media Module:

```
{
    "name": "Media",
    "alias": "media",
    "description": "",
    "keywords": [],
    "active": 0,
    "priority": 0,
    "providers": [
        "Modules\\Media\\Providers\\MediaServiceProvider"
    ],
    "aliases": {
        "Media" : "Modules\\Media\\Facades\\Media\\Facade\\Media"
    },
    "files": [
        "start.php",
        "helpers.php",
        "menu.php"
    ]
}
```

**Comment by ghprod** [comment]
@noxify Hi .. thanks a lot for your example, yes now this package has that feature :+1:
