### ISSUE TITLE
module:migrate-rollback has errors

### ISSUE THREAD

**Issue by parabol** [pingpong-labs/modules#83]
Hi again, 

the php artisan modules:migrate-rollback [modulename] has some errors. i did some manual tests about that. 

parabol@dev-mint /var/www/pyo.dev $ php artisan module:migrate-rollback

PHP Fatal error:  Class 'CreateTesterzTable' not found in /var/www/pyo.dev/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php on line 301
PHP Stack trace:
PHP   1. {main}() /var/www/pyo.dev/artisan:0
PHP   2. Symfony\Component\Console\Application->run() /var/www/pyo.dev/artisan:59
PHP   3. Symfony\Component\Console\Application->doRun() /var/www/pyo.dev/vendor/symfony/console/Symfony/Component/Console/Application.php:124
PHP   4. Symfony\Component\Console\Application->doRunCommand() /var/www/pyo.dev/vendor/symfony/console/Symfony/Component/Console/Application.php:193
PHP   5. Illuminate\Console\Command->run() /var/www/pyo.dev/vendor/symfony/console/Symfony/Component/Console/Application.php:889
PHP   6. Symfony\Component\Console\Command\Command->run() /var/www/pyo.dev/vendor/laravel/framework/src/Illuminate/Console/Command.php:100
PHP   7. Illuminate\Console\Command->execute() /var/www/pyo.dev/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
PHP   8. Pingpong\Modules\Commands\MigrateRollbackCommand->fire() /var/www/pyo.dev/vendor/laravel/framework/src/Illuminate/Console/Command.php:112
PHP   9. Pingpong\Modules\Commands\MigrateRollbackCommand->rollback() /var/www/pyo.dev/vendor/pingpong/modules/src/Pingpong/Modules/Commands/MigrateRollbackCommand.php:44
PHP  10. Illuminate\Console\Command->call() /var/www/pyo.dev/vendor/pingpong/modules/src/Pingpong/Modules/Commands/MigrateRollbackCommand.php:61
PHP  11. Illuminate\Console\Command->run() /var/www/pyo.dev/vendor/laravel/framework/src/Illuminate/Console/Command.php:128
PHP  12. Symfony\Component\Console\Command\Command->run() /var/www/pyo.dev/vendor/laravel/framework/src/Illuminate/Console/Command.php:100
PHP  13. Illuminate\Console\Command->execute() /var/www/pyo.dev/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
PHP  14. Illuminate\Database\Console\Migrations\RollbackCommand->fire() /var/www/pyo.dev/vendor/laravel/framework/src/Illuminate/Console/Command.php:112
PHP  15. Illuminate\Database\Migrations\Migrator->rollback() /var/www/pyo.dev/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/RollbackCommand.php:59
PHP  16. Illuminate\Database\Migrations\Migrator->runDown() /var/www/pyo.dev/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:172
PHP  17. Illuminate\Database\Migrations\Migrator->resolve() /var/www/pyo.dev/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:192
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'CreateTesterzTable' not found","file":"\/var\/www\/pyo.dev\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Migrations\/Migrator.php","line":301}}

**Comment by gravitano** [comment]
I think you've been solved this problem, right ? If no, you can re-open this issue.
