### ISSUE TITLE
How to use/enable Alias in a module

### ISSUE THREAD

**Issue by noxify** [pingpong-labs/modules#86]
Hi,

i have a module named "Media" which handles my ajax based upload and the file listing for a record.

Currently, I have created some macros for it.

File: Modules\Media\helpers.php
```
<?php

\Form::macro('ajaxupload', function($module="", $module_id="", $options=array('dropzone' => false))
{
    return View::make('media::upload', compact('module', 'module_id', 'options'));
});

\HTML::macro('getmedia', function($model)
{
    return View::make('media::preview', compact('model'));
});
```

The helpers.php is also in the "files" array inside the module.json.

This works fine and I can use with `{{ Form::ajaxupload() }}` and `{{ HTHML::getmedia() }}`

But now my plan was to create my own commands like `{{ Media::upload() }}` and `{{ Media::list() }}`.

I have created for this the following:

File: Modules\Media\Providers\MediaServiceProvider.php
```
<?php namespace Modules\Media\Providers;

use Illuminate\Support\ServiceProvider;

class MediaServiceProvider extends ServiceProvider {

	/**
	 * Indicates if loading of the provider is deferred.
	 *
	 * @var bool
	 */
	protected $defer = false;

	/**
	 * Register the service provider.
	 *
	 * @return void
	 */
	public function register()
	{
		\App::bind('media', function()
		{
		    return new Modules\Media\Media;
		});
	}

	/**
	 * Get the services provided by the provider.
	 *
	 * @return array
	 */
	public function provides()
	{
		return array();
	}

}
```

File: Modules\Media\Fascades\Media.php
```
<?php namespace Modules\Media\Facades;

use Illuminate\Support\Facades\Facade;

class Media extends Facade {

    /**
     * Get the registered name of the component.
     *
     * @return string
     */
    protected static function getFacadeAccessor()
    {
        return 'media';
    }

}
```

File: Modules\Media\Media.php
```
<?php namespace Modules\Media;

class Media {

    public function process()
    {
        echo "hello";
    }

}
```

File: Modules\Media\module.json
```
{
    "name": "Media",
    "alias": "media",
    "description": "",
    "keywords": [],
    "active": 1,
    "priority": 0,
    "providers": [
        "Modules\\Media\\Providers\\MediaServiceProvider",
    ],
    "files": [
        "start.php",
        "helpers.php",
        "menu.php"
    ]
}
```

But even when I try to execute the `{{ Media::process() }}` command in the template I got the following Error message:

```
Class 'Media' not found
```

In a second test, I have added also an Alias to the app/config/app.php:
```
'Media' => 'Modules\Media\Fascades\Media'
```

But I got only an error :(

Has anyone a idea, how I can solve the problem?

Thanks :)

**Comment by noxify** [comment]
Btw. i saw in the Modules from @nWidart that he uses a "aliases" tag in the module.json. Maybe a new feature ;)

**Comment by nWidart** [comment]
I implemented that myself, yes. :)
But since the laravel 5 aliasloader is bugged, the aliases aren't register as they should.

**Comment by noxify** [comment]
Hi,

thanks - I'm using Laravel 4 - But maybe I got the solution with this: http://fideloper.com/create-facade-laravel-4

**Comment by nWidart** [comment]
Oh okay, the alias loader in l4 works fine.

**Comment by noxify** [comment]
Okay... currently I have integrate your functionality to add aliases :)

here the complete module: https://github.com/noxify/modules-media
(I think, it's easier for you as the code snippets ;) )

And in the `vendor/pingpong/modules/src/Pingpong/Modules/Module.php` I have added the following

```
<?php namespace Pingpong\Modules;

use Illuminate\Foundation\Application;
//NEW START
use Illuminate\Foundation\AliasLoader;
//NEW END
use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Str;
```

and
```
    public function register()
    {
        $this->registerAliases();

        $this->registerProviders();

        $this->registerFiles();

        $this->fireEvent('register');
    }

    protected function registerAliases()
    {
        $loader = AliasLoader::getInstance();
        \Debugbar::info($this->get('aliases'));
        foreach ($this->get('aliases', []) as $aliasName => $aliasClass)
        {

            $loader->alias($aliasName, $aliasClass);
        }
    }
```

then I have run `composer dump-autoload` and also `php artisan dump-autoload` to be sure :)

But If I try to get the result from my `process()` function via `{{ Media::process() }}`
I got always the following error:

```
Call to undefined method Modules\Media\Facades\Media\Facade\Media::process()
```

Which means, for me, that the process() function does not exists in the Facade/Media.php --> This is correct, because it should use the Media.php

Don't know, what's wrong here - maybe anyone has a idea :)


Thanks.

**Comment by nWidart** [comment]
Hm I see you service provider is empty. You should at least let laravel now what to use when you call the Media facade. 
You used `"Media" : "` but is `Media` actually bound in the IoC container ?

Something like [this](https://github.com/AsgardCms/Media/blob/develop/Image/ImageServiceProvider.php#L26)

**Comment by noxify** [comment]
@nWidart - thanks a lot! It's working now.
I have updated my repo with the working code :)

**Comment by nWidart** [comment]
Great :smiley:

**Comment by noxify** [comment]
soo.. now i will create a pull request for the modules :)
