### ISSUE TITLE
[L5] Error when creating a module - Config not loading

### ISSUE THREAD

**Issue by TheTechnoMan** [pingpong-labs/modules#90]
Hello,

C:\xampp\htdocs\XX>php artisan module:make blog
exception 'ErrorException' with message 'array_values() expects parameter 1 to be array, null given' in C:\xampp\htdocs\XX\vendor\pingpong\modules\src\Pingpong\Modules\Generators\ModuleGenerator.php:202

I assume the error occurs because 5 does not longer provide a way to publish the config with a command: http://laravel.io/forum/01-16-2015-laravel-5-package-configuration

Thanks

**Comment by TheTechnoMan** [comment]
Maybe the error occurs because the config has not been published?

L5 does not longer provide a way to publish the config with a command: http://laravel.io/forum/01-16-2015-laravel-5-package-configuration

Thanks

**Comment by nWidart** [comment]
Laravel 5 support isn't finished yet. Lot's has changed for package developers in laravel 5. 
Please be patient, support will come. :)

**Comment by TheTechnoMan** [comment]
Yeah I know. However it is not almost done as Taylor said on his recent Q&A. He even said that no big changes will be made anymore until the release, so it is safe to use now. Looking forward for a fix :)

Thank you very much

**Comment by nWidart** [comment]
Finally, some documentation about packages :) http://laravel.com/docs/master/packages

**Comment by TheTechnoMan** [comment]
@gravitano any updates? 

Thanks!

**Comment by nWidart** [comment]
I've successfully updated one of [my packages](https://github.com/nWidart/Laravel-broadway) to laravel 5, and I can say it wasn't as difficult as I though it would be.

**Comment by TheTechnoMan** [comment]
@gravitano A reply would be really appreciated as L5 is (almost) done now.

**Comment by gravitano** [comment]
Today, I am working with fixing a few of bugs and improvement for full support with L5. Thanks!

**Comment by TheTechnoMan** [comment]
Awesome. Just a general question, how does a get/post route need to look like when referring to the module?

Thanks
