### ISSUE TITLE
How to change the path to the *.stub files

### ISSUE THREAD

**Issue by noxify** [pingpong-labs/modules#91]
Hi,

is it possible to change the path to the *.stub files without changing it in the vendor package?
Maybe it would be good to have this path also in the paths config?

Thanks :)

**Comment by nWidart** [comment]
To generate custom ones?

Yeah that annoyed me too, for my module generator feature : http://quick.as/loki7l0 .
The how-to can be found [here](https://github.com/AsgardCms/Workshop/blob/develop/Console/ScaffoldCommand.php) , I pretty much had to remove everything pingpong/modules makes when a module gets generated.

Maybe it would be -super- nice if , just like in laravel 5, there is a ---clean flag, which when set, doesn't generate all the unneeded files everywhere.

**Comment by noxify** [comment]
awesome @nWidart - looks very good :)

Maybe in the evening i have some time to test something with the pingpong modules package,
maybe the solution is easier as I think :)

**Comment by noxify** [comment]
got it :)

I will create the PR in the evening, now I have to work at work :D
