### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by TheTechnoMan** [pingpong-labs/modules#93]
Hey,

here are some bugs that I encounterd:

1) Some of the generated files are not in the correct directroy. For example the Controller, the DatabaseSeeder and the ServiceProvider are in the main folder instead of the Http/Controllers, Database/Seeders and Providers.

2) It looks like that the paths are not registered correctly under L5. Whenever I try to load a view I get a ` InvalidArgumentException in FileViewFinder.php line 112: No hint path defined for [ModuleName].`
I resolved this by adding this to the register method at Providers/ModuleNameServiceProvider.php
`$this->loadViewsFrom(__DIR__.'/../Resources/views', 'ModuleName');`

3) The ServiceProviders is not registered in the Proviers key at the modules json file.

**Comment by gravitano** [comment]
Hi,

In the latest commit of this repo (in 2.0.x branch), I have been removed `package` method in `Pingpong\Modules\Module` class, which in that method is contain a way to add new view's namespace. And now we need to add view's namespace manually. Also the config and translator namespaces were removed. 

To fix the `hint not defined` issue, just add namespace manually in your module's start.php file. For example:

```
Lang::addNamespace('blog', __DIR__.'/Resources/views');

View::addNamespace('blog', __DIR__.'/Resources/views');
```

For fix the first issue, i will push new commit for it.

Thanks

**Comment by TheTechnoMan** [comment]
Yeah, I did it similar as explained above. However, the ServiceProvider is still not in the Providers dir after the update ;)

**Comment by nWidart** [comment]
Look at the new way of defining view namespaces : http://laravel.com/docs/master/packages#views :)

**Comment by TheTechnoMan** [comment]
@nWidart I guess you are confusing something. The problem with the views has been fixed already ;)

**Comment by nWidart** [comment]
Oh okay, my bad.

**Comment by TheTechnoMan** [comment]
Don't worry :P

**Comment by cracki** [comment]
hi
i am testing in windows environment.

there is different between blog and Blog
by default creating module by:
php artisan module:make blog 
get this error
No hint path defined for [Blog].
by adding this:
$this->loadViewsFrom(__DIR__.'/../Resources/views', 'blog');
no change, but by this:
$this->loadViewsFrom(__DIR__.'/../Resources/views', 'Blog');
(blog=>Blog)
worked !
