### ISSUE TITLE
2.0@dev installation

### ISSUE THREAD

**Issue by nWidart** [pingpong-labs/modules#94]
Hello,

I tried installing the 2.0 version for laravel 5, but I'm getting this error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for pingpong/modules 2.0.*@dev -> satisfiable by pingpong/modules[2.0.x-dev].
    - pingpong/modules 2.0.x-dev requires illuminate/html master -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

```

Manually adding ` "illuminate/html": "5.0.*@dev",` to the composer file fixed it. Maybe it could be included in this pingpong/modules package.

**Comment by nWidart** [comment]
Also, I've added a service provider to the providers array in module json, but it doesn't get loaded by pingpong/modules.

``` json
{
    "name": "Parts",
    "alias": "parts",
    "description": "",
    "keywords": [],
    "active": 0,
    "priority": 0,
    "providers": [
      "Modules\\Parts\\PartServiceProvider"
    ],
    "files": [
    ]
}
```

**Comment by nWidart** [comment]
Also, the Facade wasn't registered.
With doing the following it worked:

```php
$loader = AliasLoader::getInstance();
$loader->alias('Module', 'Pingpong\Modules\Facades\Module');
```

**Comment by gravitano** [comment]
Hi, thank for your feedback. I'll fix this soon as possible. Btw, for now the facade need to registered manually. I think I will make it automatically registered. 

Thanks

**Comment by nWidart** [comment]
Indeed, same for the Form facade. (and guessing the HTML one too)
