### ISSUE TITLE
Laravel 5 - dev2.0 - Command "module:publish-config" is not defined.

### ISSUE THREAD

**Issue by koray-mobven** [pingpong-labs/modules#96]
Hello,

I applied installation steps for Laravel 5 but it gives "exception 'InvalidArgumentException' with message 'Command "module:publish-config" is not defined." error when i run "module:publish-config" command.

**Comment by gravitano** [comment]
Hi, that command has been removed. Use `php artisan vendor:publish` instead. I haven't updated wiki page.

**Comment by koray-mobven** [comment]
Thanks.
