### ISSUE TITLE
Class Modules\Customer\Http\Controllers\XXXController does not exist

### ISSUE THREAD

**Issue by koray-mobven** [pingpong-labs/modules#97]
Hi,

I installed v2.0@dev and created a module named customer using artisan command. All files looks ok but it gives "Class Modules\Customer\Http\Controllers\CustomerController does not exist" when i type localhost/customer to browser. I checked and CustomerController file exists. No any route with same path. Why this happens?

Thanks.

**Comment by gravitano** [comment]
Have you added `PSR-4` autoloading for modules folder ?

**Comment by koray-mobven** [comment]
Yes, i added it to composer.son file.

It looks like:

"autoload": {
		"classmap": [
			"database"
		],
		"psr-4": {
			"App\\": "app/",
                        "Modules\\": "Modules"
		}
	},

**Comment by gravitano** [comment]
Please follow this https://github.com/pingpong-labs/modules/wiki/Installation#autoloading

**Comment by gravitano** [comment]
have you ran `composer dump-autoload`?

**Comment by koray-mobven** [comment]
Hmm i forgot composer dump-autload.
It should be add to documentation.

It gives "No hint path defined for [customer]." error now.

**Comment by gravitano** [comment]
For `no hint defined` issue, please see this https://github.com/pingpong-labs/modules/issues/93. I haven't updated the generated files for each module yet.

**Comment by gravitano** [comment]
I'll fix that issue as soon as possible.

**Comment by koray-mobven** [comment]
Thanks. I'll follow updates.
