### ISSUE TITLE
Unable to load config settings from module

### ISSUE THREAD

**Issue by grafikkaos** [pingpong-labs/modules#99]
I have a modules (called Settings) which is used to save site values to a database.  I am trying to load certain values from the module i.e. Config::get('settings::site_settings.meta_author') but it looks like that modules is not even being loaded.

Any ideas around this problem?

Thanks

**Comment by RMK147** [comment]
+1 I'm also having this problem

**Comment by noxify** [comment]
Laravel 4 or Laravel 5?

**Comment by RMK147** [comment]
Laravel 5

**Comment by grafikkaos** [comment]
Laravel 5

**Comment by gravitano** [comment]
Hi, 

In Laravel 5 there is no namespace autoloading for config anymore. You need to register the config manually, something like this http://laravel.com/docs/5.0/packages#configuration. I think add some snippet for you if you want.

**Comment by grafikkaos** [comment]
Hi,

I take it you mean doing something like this in the modules' service provider:

public function register()
{
        $this->registerConfiguration();
}

private function registerConfiguration()
    {
        $configPath = __DIR__ . '/../config/site_settings.php';
        $this->mergeConfigFrom($configPath, 'site_settings');
        $this->publishes([$configPath => config_path('site_settings.php')]);
    }

I have done that but settings from the module are still not accessible..

**Comment by gravitano** [comment]
Of course I have done it. Take a look to this file. https://github.com/pingpong-labs/modules/blob/2.0/Commands/stubs/scaffold/provider.stub

That file is used for generating service provider when you run `module:make` command.

**Comment by grafikkaos** [comment]
That seems to have fixed the issue.  Thanks for the hard work :+1:
